GET  http://localhost:5000/api/patients/appointments/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MmE5Y2ZjYzQ4YWM1NzY1ODI4MjFkZCIsInJvbGUiOiJwYXRpZW50IiwicGF0aWVudElkIjoiNjkyYTljZmNjNDhhYzU3NjU4MjgyMWRiIiwiaWF0IjoxNzY0NDE3MTA5LCJleHAiOjE3NjUwMjE5MDl9._qel9EzNgztKJRAMYcvLrujes8Gpljm4JH6F5Vf15j0
Accept: application/json

###



GET http://localhost:5000/api/patients/profile/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MmE5Y2ZjYzQ4YWM1NzY1ODI4MjFkZCIsInJvbGUiOiJwYXRpZW50IiwicGF0aWVudElkIjoiNjkyYTljZmNjNDhhYzU3NjU4MjgyMWRiIiwiaWF0IjoxNzY0NDE3MTA5LCJleHAiOjE3NjUwMjE5MDl9._qel9EzNgztKJRAMYcvLrujes8Gpljm4JH6F5Vf15j0
Accept: application/json

###
GET http://localhost:5000/api/appointments/doctor/my-appointments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MmFjZTQwZWNhNjI4MDRlZWMxYmM0NiIsInJvbGUiOiJkb2N0b3IiLCJkb2N0b3JJZCI6IjY5MmFjZTQxZWNhNjI4MDRlZWMxYmM0OCIsImlhdCI6MTc2NDU4MTg4OCwiZXhwIjoxNzY1MTg2Njg4fQ.5NLVqkw6YPX4fIPgvMDpPGurufY6z22HNzcOto0bMEQ
Accept: application/json